# Generated by Django 4.0.4 on 2022-05-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0004_alter_familia_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='familiares'),
        ),
    ]
